-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 11:08:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema food_court
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_court
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_court` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `food_court` ;

-- -----------------------------------------------------
-- Table `food_court`.`chief`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_court`.`chief` (
  `stt_chief` INT NOT NULL AUTO_INCREMENT,
  `id_chief` INT NOT NULL,
  `name_chief` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `birthDate_chief` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_chief`),
  UNIQUE INDEX `stt_chief_UNIQUE` (`stt_chief` ASC) VISIBLE,
  UNIQUE INDEX `id_chief_UNIQUE` (`id_chief` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_court`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_court`.`food` (
  `stt_food` INT NOT NULL AUTO_INCREMENT,
  `id_food` INT NOT NULL,
  `name_food` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `quantities_food` INT NULL DEFAULT NULL,
  `price_food` INT NULL DEFAULT NULL,
  `description_food` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `id_chief` INT NOT NULL,
  PRIMARY KEY (`id_food`),
  UNIQUE INDEX `id_food_UNIQUE` (`id_food` ASC) VISIBLE,
  UNIQUE INDEX `stt_food_UNIQUE` (`stt_food` ASC) VISIBLE,
  INDEX `id_chief_idx` (`id_chief` ASC) VISIBLE,
  CONSTRAINT `food_id_chief`
    FOREIGN KEY (`id_chief`)
    REFERENCES `food_court`.`chief` (`id_chief`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_court`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_court`.`order` (
  `stt_order` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NOT NULL,
  `dateTime_date` DATETIME NULL DEFAULT NULL,
  `name_customer` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `name_food` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `quantities_food` INT NULL DEFAULT NULL,
  `confirmed` TINYINT NULL DEFAULT NULL,
  `done` TINYINT NULL DEFAULT NULL,
  `id_chief` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  UNIQUE INDEX `id_order_UNIQUE` (`id_order` ASC) VISIBLE,
  UNIQUE INDEX `stt_order_UNIQUE` (`stt_order` ASC) VISIBLE,
  INDEX `id_chief_idx` (`id_chief` ASC) VISIBLE,
  CONSTRAINT `order_id_chief`
    FOREIGN KEY (`id_chief`)
    REFERENCES `food_court`.`chief` (`id_chief`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
